### ISSUE TITLE
Broken in Chrome Version 49.0.2616.0 canary (64-bit)

### ISSUE THREAD

**Issue by LinusU** [feross/drag-drop#10]
`example.html` (and my own code) doesn't work in Chrome Version 49.0.2616.0 canary (64-bit). It seems like the `entry.file` callback never gets called.

Investigating more now...

**Comment by LinusU** [comment]
**FileError**

- code: 5
- message: "A URI supplied to the API was malformed, or the resulting Data URL has exceeded the URL length limitations for Data URLs."
- name: "EncodingError"

-----

At first I was trying with a rather large image file, but trying with a shorter text file and even an empty file produces the same error.

The quest continues!

**Comment by LinusU** [comment]
So it turns out that this error really means "Don't use the file://" protocol. I wasn't serving my html over http, but instead just opened the file in chrome. That apparently doesn't work...

**Comment by feross** [comment]
Yep that's right. I'll add a note to the readme about that particular Chrome quirck.

**Comment by LinusU** [comment]
Thank you!
