### ISSUE TITLE
If non-file (link, text, etc) is dropped, causes error

### ISSUE THREAD

**Issue by 0x00A** [feross/drag-drop#17]
Specifically, `TypeError: Cannot read property 'isFile' of null`, from [`here`](https://github.com/feross/drag-drop/blob/master/index.js#L100-L110). Possible fix could be to just check for `entry`.

**Comment by feross** [comment]
@0x00A I tried to fix this exact issue already in https://github.com/feross/drag-drop/commit/44a52300b2c4805b5fbe05e7f1bef4aaf109acae

- Could you confirm that you're using the latest version of `drag-drop` (2.8.0)?
- Could you share the browser / browser version are you using so I can try to reproduce?

Cheers!

**Comment by 0x00A** [comment]
Agh! so sorry, I was on an older version :( This works in 2.8.0 :+1:

**Comment by feross** [comment]
No problem! :smile:

**Comment by quasivivo** [comment]
I just ran into this same issue when attempting to drop empty files.
