### ISSUE TITLE
File name undefined

### ISSUE THREAD

**Issue by Thor99** [feross/drag-drop#2]
i have this:
var dragDrop = require('drag-drop');

dragDrop('#target', function (file) {
  console.log('Here are the dropped files ' + file.name);
});

When i drop a single file, the console returns: "Here are the dropped files undefined"
How can i fix it? Thanks!

**Comment by feross** [comment]
The parameter is an array of files, not a file. Try this:

```js
dragDrop('#target', function (files) {
console.log('Here is the first dropped file ' + files[0].name);
});
```
