### ISSUE TITLE
Remove the drag class when the drag+drop stops

### ISSUE THREAD

**Issue by dcposch** [feross/drag-drop#21]
The `drag` class is convenient, but for now it looks like stays even if the user stops dragging something over the app. We should remove it when that happens.

**Comment by feross** [comment]
This is likely an Electron-only issue. This behaves correctly in all browsers on https://instant.io.

**Comment by feross** [comment]
webtorrent-app issue: https://github.com/feross/webtorrent-app/issues/75

**Comment by feross** [comment]
This is fixed in https://github.com/feross/drag-drop/commit/d65c46de966ceb36e5fedc0a8e539de8be6c0dfe

**Comment by feross** [comment]
Released as 2.11.0
