### ISSUE TITLE
FullPath always on root directory

### ISSUE THREAD

**Issue by kanekotic** [feross/drag-drop#27]
I have been trying to use this library and the fullPath always shows (`/<name of file>`), from what I see from the code this seems to be by design:
```js
files.forEach(function (file) {
    file.fullPath = '/' + file.name
})
```
https://github.com/feross/drag-drop/blob/ff165698e802bd032b9d0dc9e79c7eb0eefee6a6/index.js#L130-L132

In my case I need to start a process external that requires the full path to a file `<Path to file>/<name of file>`. 

is this something possible? is the fullpath not as intended? or is it possible to add another property with this `fullPath`

thanks in advance for your help.

**Comment by feross** [comment]
Are you trying to use this on the web? Which browser? Which browser version? Or in Electron?

**Comment by kanekotic** [comment]
i am using it on a web accesible on the browser and also a qt application. I have seen this behaviour in Chrome and Qtwebengine. Both on OSX sierra.
 Wen i arrive home i will give you the specific version and also test firefox and safari. But is kind of consistent in the 2 I have tested.

**Comment by kanekotic** [comment]
here is a repo with the code that allows me to reproduce it: https://github.com/kanekotic/drag_drop_error
its consistently reproducible in all browsers under `OSX Sierra`. This means tested in:
 - `safari -> 10.0.1 (12602.2.14.0.7)`
 - `chrome -> 55.0.2883.95 (64-bit)`
 - `firefox -> 50.1.0` 
 - `QtWebEngine -> 5.7`

The file to be able to test is on the repo, and the behaviour is that the output for fullpath is always: `[{"fullPath":"/TEST.mp4"}]`

**Comment by feross** [comment]
You can't get the full path of a drag-and-dropped file on the web, for security reasons. The is enforced by the browser itself. The full path could reveal info like your full name, for example:

`/Users/John Doe/Documents/my-file.txt`

That said, if you're using QtWebEngine, there might be a way to get the full path. Since I don't use it, I can't help you there. In Electron, which is similar, the full path is actually set to the real path on the system.

**Comment by feross** [comment]
Also, for the record: the `file.fullPath = '/' + file.name` code only runs in browsers that don't support the Entries API, since those browsers don't set a `fullPath` property at all. We set it so it's consistent.

**Comment by kanekotic** [comment]
thanks a lot for the response @feross
