### ISSUE TITLE
drag-drop/buffer drop "fullPath" property

### ISSUE THREAD

**Issue by azu** [feross/drag-drop#30]
`drag-drop`'s result have `file.fullPath`.
```js
var dragDrop = require('drag-drop')
dragDrop('#dropTarget', function (files) {
  files.forEach(function (file) {
    console.log(file.fullPath)
  })
})
```

But, `drag-drop/buffer`'s result not have `fullPath`

```js
var dragDrop = require('drag-drop/buffer')
dragDrop('#dropTarget', function (files) {
  files.forEach(function (file) {
    console.log(file.fullPath) // undefined
  })
}
```

- https://github.com/feross/drag-drop/blob/250dd93515e8e7c3af1d1297cb0e4d63dbd579bd/buffer.js#L13-L16

Is this expected design?

**Comment by feross** [comment]
This was an oversight. Thanks for reporting. Fixed in 2.13.2.

**Comment by feross** [comment]
https://github.com/feross/drag-drop/commit/442eacc80c6c0768eecea83504915b8a591527e6

**Comment by azu** [comment]
Thanks!
