### ISSUE TITLE
Can't drag & drop with nw and frame disabled

### ISSUE THREAD

**Issue by bil-elmoussaoui** [feross/drag-drop#32]
It seems that I can't use drag-drop when I disable frame in package.json. Even if i set the draggable id as `-webkit-app-region: drag;`
My package.json
```json
{
    "name": "Test",
    "main": "app/index.html",
    "window": {
        "width": 380,
        "height": 380,
        "frame": false,
        "resizable": false,
        "toolbar": false
    },
    "dependencies": {
        "drag-drop": "^2.13.2",
        "file-type": "^4.1.0",
        "font-awesome": "^4.7.0",
        "read-chunk": "^2.0.0"
    }
```

With the same code if i turn frame to true everything works as expected.

**Comment by feross** [comment]
Sorry, I don't know how this NW.js option works, and I can't provide free support for it. I suggest asking the NW.js team / reading the docs about the frame option to learn how it affects drag handlers.

**Comment by bil-elmoussaoui** [comment]
@feross Sorry for that! I just figured it out; it does work as expected now! Many thanks

**Comment by feross** [comment]
Great :)
