### ISSUE TITLE
Large files crash the browser (Chromium)

### ISSUE THREAD

**Issue by alec-chan** [feross/drag-drop#33]
I'm trying to use drag-drop as seen in your WebTorrent README, to upload a file for seeding.  It works just fine for files under ~300MB, but files pushing ~500MB alway cause the page to crash in Chrome.  Firefox seems to be able to handle the larger files.  Is this some kind of limitation with Chrome?  Should I be using buffers to mitigate this?  If so, how do I actually use buffers with drag-drop?  I don't use browserify, and I'm not sure how to do the equivalent of require('drag-drop/buffer'), do I just <include> the buffer.js file?

**Comment by feross** [comment]
The crashing behavior used to be an issue but I just tested with a 1.2 GB file and I don't see any crashes.
