### ISSUE TITLE
Only fallback to proprietary webkit FS API if standard API is not available

### ISSUE THREAD

**Issue by benjamin-demarteau** [feross/drag-drop#37]
In https://github.com/feross/drag-drop/blob/6f563124d468cdaa0fae7b9d33f3fc1f30e56010/index.js#L113, the code steps in the webkit fs api if it's available before checking if the standard way to do it works.

Reversing the branches here based on `e.dataTransfer.files` would allow library users to listen for file drops and set an `input[type=file]`'s selection to that (which is only supported by browsers for `FileList` as a security measure).

**Comment by feross** [comment]
I saw your PR here: https://github.com/feross/drag-drop/pull/38 Let's continue discussion there. Closing this issue.
