### ISSUE TITLE
HTML5 drag and drop API link in README.md file links to wrong page.

### ISSUE THREAD

**Issue by BobbyBabes** [feross/drag-drop#42]
The `HTML5 drag and drop API` link at the top of the README.md file should point to : [https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)

**Comment by feross** [comment]
Thanks, fixed.
