### ISSUE TITLE
OSX Safari 11.1.2: drag class not appended on dragover

### ISSUE THREAD

**Issue by andrejpavlovic** [feross/drag-drop#43]
By going to https://instant.io/ and dragging any file over the page, it doesn't show the red overlay that is shown in other browsers when the same is tried.

**Comment by alexeikaratai** [comment]
e.dataTransfer doesn't support on safari. Could u fix it?

**Comment by chrismadrigal** [comment]
Experiencing the same issue here. Any fix for this? 🙏

**Comment by feross** [comment]
👋 Thanks for opening an issue. This project is a volunteer-run effort. I don't have any immediate plans to work on this issue.

However, I noticed you work for a for-profit company. Please consider asking your company to allocate resources toward fixing this issue and submitting a PR. I'll be happy to review any PR you contribute here. ❤️

**Comment by feross** [comment]
This issue is fixed in the latest version, 6.1.0.
