### ISSUE TITLE
drag-drop.min.js missing from latest release

### ISSUE THREAD

**Issue by neokio** [feross/drag-drop#54]
**Release 5.0.2** ... https://github.com/feross/drag-drop/tree/v5.0.2 ... features dragdrop.min.js. This works as expected.

**Release 6** ... https://github.com/feross/drag-drop ... has nothing. No minified or otherwise working code. I thought maybe index.js was your new release, which seemed strange, so I minified it and tested. But after getting a "module is undefined" error and looking deeper, I realized you probably just forgot to add it to the codebase. So my NPM update left me high and dry :)

Reinstalling with `npm i drag-drop@5 --save` is my temporary workaround. I'd love to know what you did in v6! You should comment your major releases so we can get excited and cheer you on.

**Comment by neokio** [comment]
Just checked out your resumé. Holy crap.

**Comment by neokio** [comment]
Seriously though, what am I missing? `drag-drop.js` is entirely missing, it's even in the gitignore ...

**Comment by Raynos** [comment]
https://github.com/feross/drag-drop/commit/f1151d8681553c2defc22ff2562155ca837892aa

There's a commit recommending https://bundle.run/drag-drop

**Comment by Raynos** [comment]
I'd recommend removing this package from package.json if your not using a bundler.

`npm rm drag-drop --save`

Then just create a `vendor/drag-drop.js` with the code from https://bundle.run/drag-drop@6.0.2

Feel free to add

```js
// Manually copied from https://bundle.run/drag-drop@6.0.2
```

To the top of the file to make it easier to understand where it came from.
