### ISSUE TITLE
nw.js: document is not defined

### ISSUE THREAD

**Issue by PimpShanti** [feross/drag-drop#7]
I'm a bit new to all this so it's probably an issue with my (lack of) understanding of nw.js or JS in general but any pointers are appreciated!

I tried require()ing in the normal way and upon running my app I am told:

"Uncaught ReferenceError: document is not defined".

I have also tried linking to the dragdrop.bundle.js as the src of a script element but I am a little unsure what the line "This exports a DragDrop function on window" means and so I'm not sure I have tried to use it properly. The error I am getting reads:

"Uncaught TypeError: Cannot read property 'addEventListener' of null".

I would really like to use your module rather than the clunky offerings from HTML5 (which do seem to be working for me)! Thanks for any help you can offer.

**Comment by feross** [comment]
I think that in nw.js you always need to refer to things as either on `window` (browser context) or `global` (node.js context). So, inside this module we use `document` instead of `window.document`.

I just attempted to fix that for you. Can you try updating to the latest drag-drop v2.3.1 and try again?

`npm install drag-drop`

**Comment by feross** [comment]
Also, if you still want to go with the script tag approach, "This exports a DragDrop function on window" just means that you can use DragDrop by referencing it on the `window` object.

```html
<script src="/path/to/dragdrop.bundle.js"></script>
<script>
window.DragDrop() // use it like documented in the readme
</script>
```

**Comment by PimpShanti** [comment]
That was an insanely fast response, thanks! Just updated my initial comment with the error message when using the script tag approach (in the way you mention).

"Uncaught TypeError: Cannot read property 'addEventListener' of null".

Will try the updated drag-drop now, thanks again.

**Comment by PimpShanti** [comment]
Have just updated 2.3.1 and now I'm getting the same error message for both require() and script element methods:

TypeError: Cannot read property 'addEventListener' of null
    at r (./node_modules/drag-drop/dragdrop.bundle.js:1:4489)

Thanks

**Comment by PimpShanti** [comment]
In case any other noobs run into similar issues, the solution to my problem was to put the script AFTER the div I was targeting. 

Thanks again @feross for so quickly updating the module to work within nw.js, I'm underway now and drag-drop is already proving very useful

**Comment by feross** [comment]
@PimpShanti Glad you got this working!
